name: Static check source code

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements/*'
      - name: Install requirements
        run: 'python -m pip install -r requirements/dev.txt'
      - name: Black
        run: 'black bot --check --color'
      - name: Ruff
        run: 'ruff bot'
      - name: Mypy
        run: 'mypy bot'
