name: Static check source code

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements/*'
      - name: Install requirements
        run: 'python -m pip install -r requirements/dev.txt'
      - name: Cache linter caches
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-linters
          path: |
            .mypy_cache
            .ruff_cache

      - name: Black
        run: 'black bot --diff --color'
      - name: Ruff
        run: 'ruff bot --format github'
      - name: Mypy
        run: 'mypy bot'
